name: Deploy Preview to Vercel

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if you're using Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use the appropriate Node.js version for your project

      - name: Install dependencies (if using Node.js)
        run: npm install

      - name: Deploy to Vercel (Preview Deployment)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: wisp-kit-${{ github.event.pull_request.number }}.vercel.app
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
