name: Send Discord Webhook

on:
  push:
    branches:
      - main

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install @actions/core @actions/github

      - name: Run Discord Webhook Script
        id: get-modified-files
        run: node scripts/discord-webhook.js

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          raw-data: ${{ steps.get-modified-files.outputs.raw-data-path }}

      - name: Clean up raw-data file
        run: |
          rm ${{ steps.get-modified-files.outputs.raw-data-path }}
