name: Trigger Wisp Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - modules/**
      - scripts/**
      - style/**

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment in wisp
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/WispTools/wisp-web/actions/workflows/main.yml/dispatches \
               -d '{"ref":"main"}'
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: New Wisp Module Update Deployed 🚀
          embed-color: 16711680
          embed-description: |
            [
              {
                "name": "Module Name",
                "value": "${{ github.event.head_ref }}",
                "inline": true
              },
              {
                "name": "Commit Hash",
                "value": "${{ github.sha }}",
                "inline": true
              }
            ]
          embed-footer-text: ${{ github.repository }}
