name: Trigger Wisp Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - modules/**
      - scripts/**
      - style/**

jobs:
  test-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          NODE_OPTIONS: --experimental-fetch
        run: npm run test
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment in wisp-web
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/WispTools/wisp-web/actions/workflows/main.yml/dispatches \
               -d '{"ref":"main"}'
      - name: Trigger deployment in wisp-readme
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.ACTION_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/WispTools/.github/actions/workflows/update.yml/dispatches \
               -d '{"ref":"main"}'
